version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: chatbot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=chatbot
      - MYSQL_USER=chatbot
      - MYSQL_PASSWORD=chatbotpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - chatbot-network

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: chatbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - chatbot-network

volumes:
  mysql_data:
  qdrant_data:

networks:
  chatbot-network:
    driver: bridge